version: "3.8"
services: 
  identity: 
    container_name: identity
    image: casatech/supportify-backend:identity
    platform: linux/amd64
    restart: always
    environment: 
      FLASK_APP: "server.py"
      FLASK_ENV: "development"
      DEBUG: True
      JWT_SECRET: "casatech"
      JWT_TOKEN_LOCATION: "headers,cookies,json"
      JWT_COOKIE_SECURE: True
      JWT_COOKIE_HTTPONLY: True
      SECRET_KEY: "casatech"
      DB_HOST: "db_postgre"
      DB_PORT: 5432
      DB_USERNAME: "postgres"
      DB_PASSWORD: "superadmin"
      DB_DATABASE: "supportify"
      ELASTIC_URI: 'http://localhost:9200'
      UPLOAD_FOLDER: "upload"
      TIMEZONE: 'Asia/Bangkok'
    ports: 
      - "8082:5000"
    links: 
      - postgresql

  mysql: 
    container_name: db_mysql
    image: casatech/mysql:latest
    platform: linux/amd64
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: superadmin
    volumes: 
      - data_mysql:/var/lib/mysql
    ports: 
      - "3306:3306"

  postgresql: 
    container_name: db_postgre
    image: postgres:15
    platform: linux/amd64
    restart: always
    environment: 
      POSTGRES_PASSWORD: superadmin
    volumes: 
      - data_postgresql:/var/lib/postgresql/data
    ports: 
      - "5432:5432"

  elasticsearch: 
    container_name: elasticsearch
    image: elasticsearch:8.11.1
    platform: linux/amd64
    restart: always
    environment: 
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      xpack.security.enabled: false
    ports: 
      - "9200:9200"
      - "9300:9300"

  adminer: 
    container_name: adminer
    image: adminer:latest
    platform: linux/amd64
    restart: always
    ports: 
      - "8080:8080"

volumes: 
  data_mysql:
  data_postgresql: