"""empty message

Revision ID: 4810e7705285
Revises: ddaf9eaebee1
Create Date: 2023-11-29 15:03:15.911881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4810e7705285'
down_revision = 'ddaf9eaebee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ts_temp_otp',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('expired_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ts_temp_otp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ts_temp_otp_otp'), ['otp'], unique=True)

    op.create_table('ts_temp_signin',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_mail', sa.String(length=100), nullable=False),
    sa.Column('account_password', sa.String(length=250), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ts_temp_signin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ts_temp_signin_account_mail'), ['account_mail'], unique=True)
        batch_op.create_index(batch_op.f('ix_ts_temp_signin_otp'), ['otp'], unique=True)

    op.create_table('ts_temp_signup',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_code', sa.String(length=20), nullable=False),
    sa.Column('account_username', sa.String(length=100), nullable=False),
    sa.Column('account_mail', sa.String(length=100), nullable=False),
    sa.Column('account_password', sa.String(length=250), nullable=False),
    sa.Column('account_fullname', sa.String(length=100), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_code')
    )
    with op.batch_alter_table('ts_temp_signup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ts_temp_signup_account_mail'), ['account_mail'], unique=True)
        batch_op.create_index(batch_op.f('ix_ts_temp_signup_otp'), ['otp'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ts_temp_signup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ts_temp_signup_otp'))
        batch_op.drop_index(batch_op.f('ix_ts_temp_signup_account_mail'))

    op.drop_table('ts_temp_signup')
    with op.batch_alter_table('ts_temp_signin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ts_temp_signin_otp'))
        batch_op.drop_index(batch_op.f('ix_ts_temp_signin_account_mail'))

    op.drop_table('ts_temp_signin')
    with op.batch_alter_table('ts_temp_otp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ts_temp_otp_otp'))

    op.drop_table('ts_temp_otp')
    # ### end Alembic commands ###
