"""empty message

Revision ID: c02d445cd96e
Revises: f918d3531cb2
Create Date: 2023-12-05 09:18:05.668660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02d445cd96e'
down_revision = 'f918d3531cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ts_ticket', schema=None) as batch_op:
        batch_op.alter_column('submission_by',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('process_by',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ts_ticket', schema=None) as batch_op:
        batch_op.alter_column('process_by',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('submission_by',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
