"""empty message

Revision ID: ddaf9eaebee1
Revises: 
Create Date: 2023-11-29 15:00:48.831142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddaf9eaebee1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ts_account',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_code', sa.String(length=20), nullable=False),
    sa.Column('account_username', sa.String(length=100), nullable=False),
    sa.Column('account_password', sa.String(length=250), nullable=False),
    sa.Column('account_fullname', sa.String(length=100), nullable=False),
    sa.Column('account_mail', sa.String(length=100), nullable=False),
    sa.Column('account_phone', sa.String(length=20), nullable=True),
    sa.Column('privilege_code', sa.String(length=10), nullable=True),
    sa.Column('company_code', sa.String(length=10), nullable=True),
    sa.Column('client_code', sa.String(length=10), nullable=True),
    sa.Column('departement_code', sa.String(length=10), nullable=True),
    sa.Column('team_code', sa.String(length=10), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_code'),
    sa.UniqueConstraint('account_phone'),
    sa.UniqueConstraint('client_code'),
    sa.UniqueConstraint('company_code'),
    sa.UniqueConstraint('departement_code'),
    sa.UniqueConstraint('privilege_code'),
    sa.UniqueConstraint('team_code')
    )
    with op.batch_alter_table('ts_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ts_account_account_mail'), ['account_mail'], unique=True)

    op.create_table('ts_account_privilege',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('privilege_code', sa.String(length=10), nullable=False),
    sa.Column('privilege_name', sa.String(length=100), nullable=False),
    sa.Column('privilege_desc', sa.Text(), nullable=True),
    sa.Column('privilege_status', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('privilege_code')
    )
    op.create_table('ts_company',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_code', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_description', sa.Text(), nullable=True),
    sa.Column('company_address', sa.Text(), nullable=True),
    sa.Column('company_province', sa.String(length=20), nullable=True),
    sa.Column('company_city', sa.String(length=20), nullable=True),
    sa.Column('company_district', sa.String(length=20), nullable=True),
    sa.Column('company_subdistrict', sa.String(length=20), nullable=True),
    sa.Column('company_postcode', sa.String(length=20), nullable=True),
    sa.Column('company_phone', sa.String(length=20), nullable=True),
    sa.Column('company_fax', sa.String(length=20), nullable=True),
    sa.Column('company_telephone', sa.String(length=20), nullable=True),
    sa.Column('company_mail', sa.String(length=100), nullable=True),
    sa.Column('company_website', sa.String(length=100), nullable=True),
    sa.Column('company_youtube', sa.String(length=100), nullable=True),
    sa.Column('company_fb', sa.String(length=100), nullable=True),
    sa.Column('company_x', sa.String(length=100), nullable=True),
    sa.Column('company_image', sa.String(length=200), nullable=True),
    sa.Column('company_favicon', sa.String(length=200), nullable=True),
    sa.Column('company_status', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_code')
    )
    op.create_table('ts_company_client',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_code', sa.String(length=10), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('client_desc', sa.Text(), nullable=True),
    sa.Column('client_status', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_code')
    )
    op.create_table('ts_departement',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('departement_code', sa.String(length=10), nullable=False),
    sa.Column('departement_name', sa.String(length=100), nullable=False),
    sa.Column('departement_desc', sa.Text(), nullable=True),
    sa.Column('departement_status', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('departement_code')
    )
    op.create_table('ts_email_setup',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticket_type', sa.String(length=10), nullable=False),
    sa.Column('ticket_status', sa.String(length=10), nullable=False),
    sa.Column('ticket_priority', sa.String(length=10), nullable=False),
    sa.Column('mail_subject', sa.Text(), nullable=True),
    sa.Column('mail_body', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ts_parameter',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('param_code', sa.String(length=10), nullable=False),
    sa.Column('param_name', sa.String(length=100), nullable=False),
    sa.Column('param_status', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('param_code')
    )
    op.create_table('ts_parameter_detail',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('param_code_detail', sa.String(length=10), nullable=False),
    sa.Column('param_code', sa.String(length=10), nullable=False),
    sa.Column('param_desc', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('param_code'),
    sa.UniqueConstraint('param_code_detail')
    )
    op.create_table('ts_sla',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticket_type', sa.String(length=10), nullable=False),
    sa.Column('ticket_status', sa.String(length=10), nullable=False),
    sa.Column('ticket_priority', sa.String(length=10), nullable=False),
    sa.Column('estimated_days', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ts_team_support',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_code', sa.String(length=10), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('team_desc', sa.Text(), nullable=True),
    sa.Column('team_status', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_code')
    )
    op.create_table('ts_team_support_client',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_code', sa.String(length=10), nullable=False),
    sa.Column('company_code', sa.String(length=10), nullable=False),
    sa.Column('client_code', sa.String(length=10), nullable=False),
    sa.Column('account_code', sa.String(length=10), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_code'),
    sa.UniqueConstraint('client_code'),
    sa.UniqueConstraint('company_code'),
    sa.UniqueConstraint('team_code')
    )
    op.create_table('ts_ticket',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticket_no', sa.String(length=10), nullable=False),
    sa.Column('ticket_subject', sa.String(length=250), nullable=False),
    sa.Column('ticket_type', sa.String(length=10), nullable=False),
    sa.Column('ticket_status', sa.String(length=10), nullable=False),
    sa.Column('ticket_priority', sa.String(length=10), nullable=False),
    sa.Column('ticket_author', sa.String(length=20), nullable=False),
    sa.Column('ticket_assignee', sa.String(length=20), nullable=False),
    sa.Column('ticket_start_date', sa.DateTime(), nullable=True),
    sa.Column('ticket_finish_date', sa.DateTime(), nullable=True),
    sa.Column('ticket_estimed_time', sa.Integer(), nullable=True),
    sa.Column('ticket_progress', sa.Integer(), nullable=True),
    sa.Column('ticket_desc', sa.Text(), nullable=True),
    sa.Column('ticket_attachment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('departement_code', sa.String(length=10), nullable=False),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('submission_by', sa.Integer(), nullable=True),
    sa.Column('process_date', sa.DateTime(), nullable=True),
    sa.Column('process_by', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('departement_code'),
    sa.UniqueConstraint('ticket_no')
    )
    op.create_table('ts_ticket_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticket_no', sa.String(length=10), nullable=False),
    sa.Column('ticket_subject', sa.String(length=250), nullable=False),
    sa.Column('ticket_type', sa.String(length=10), nullable=False),
    sa.Column('ticket_status', sa.String(length=10), nullable=False),
    sa.Column('ticket_priority', sa.String(length=10), nullable=False),
    sa.Column('ticket_author', sa.String(length=20), nullable=False),
    sa.Column('ticket_assignee', sa.String(length=20), nullable=False),
    sa.Column('ticket_start_date', sa.DateTime(), nullable=True),
    sa.Column('ticket_finish_date', sa.DateTime(), nullable=True),
    sa.Column('ticket_estimed_time', sa.Integer(), nullable=True),
    sa.Column('ticket_progress', sa.Integer(), nullable=True),
    sa.Column('ticket_desc', sa.Text(), nullable=True),
    sa.Column('ticket_attachment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('departement_code', sa.String(length=10), nullable=False),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('submission_by', sa.Integer(), nullable=True),
    sa.Column('process_date', sa.DateTime(), nullable=True),
    sa.Column('process_by', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('departement_code'),
    sa.UniqueConstraint('ticket_no')
    )
    op.create_table('ts_ticket_message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticket_no', sa.String(length=10), nullable=False),
    sa.Column('message_from', sa.String(length=20), nullable=False),
    sa.Column('message_to', sa.String(length=20), nullable=False),
    sa.Column('message_subject', sa.String(length=100), nullable=False),
    sa.Column('message_description', sa.Text(), nullable=False),
    sa.Column('message_attachment', sa.String(length=200), nullable=False),
    sa.Column('message_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_no')
    )
    op.create_table('ts_token_blacklist',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.String(length=250), nullable=False),
    sa.Column('refresh_token', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ts_token_blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ts_token_blacklist_access_token'), ['access_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_ts_token_blacklist_refresh_token'), ['refresh_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ts_token_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ts_token_blacklist_refresh_token'))
        batch_op.drop_index(batch_op.f('ix_ts_token_blacklist_access_token'))

    op.drop_table('ts_token_blacklist')
    op.drop_table('ts_ticket_message')
    op.drop_table('ts_ticket_log')
    op.drop_table('ts_ticket')
    op.drop_table('ts_team_support_client')
    op.drop_table('ts_team_support')
    op.drop_table('ts_sla')
    op.drop_table('ts_parameter_detail')
    op.drop_table('ts_parameter')
    op.drop_table('ts_email_setup')
    op.drop_table('ts_departement')
    op.drop_table('ts_company_client')
    op.drop_table('ts_company')
    op.drop_table('ts_account_privilege')
    with op.batch_alter_table('ts_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ts_account_account_mail'))

    op.drop_table('ts_account')
    # ### end Alembic commands ###
