"""empty message

Revision ID: e1de8e4a1956
Revises: 4810e7705285
Create Date: 2023-11-29 15:26:26.109214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1de8e4a1956'
down_revision = '4810e7705285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ts_temp_signin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expired_time', sa.DateTime(), nullable=False))

    with op.batch_alter_table('ts_temp_signup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expired_time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ts_temp_signup', schema=None) as batch_op:
        batch_op.drop_column('expired_time')

    with op.batch_alter_table('ts_temp_signin', schema=None) as batch_op:
        batch_op.drop_column('expired_time')

    # ### end Alembic commands ###
