"""empty message

Revision ID: f918d3531cb2
Revises: 
Create Date: 2023-12-04 17:05:15.177912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f918d3531cb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ts_ticket', schema=None) as batch_op:
        batch_op.drop_constraint('ts_ticket_departement_code_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ts_ticket', schema=None) as batch_op:
        batch_op.create_unique_constraint('ts_ticket_departement_code_key', ['departement_code'])

    # ### end Alembic commands ###
